### ISSUE TITLE
Could you give us more explanataion on how to use this api

### ISSUE THREAD

**Issue by MusLead** [mrsofiane/mawaqit-api#7]
I tried to run using
```sh
uvicorn main:app
INFO:     Started server process [5763]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     127.0.0.1:49399 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:49399 - "GET /favicon.ico HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:49401 - "GET / HTTP/1.1" 404 Not Found
```

But as you see, it returns 404 not found.

could you also give us some more explanation on how to use this uvicorn for this purpose?

**Comment by MusLead** [comment]
as I tried to run this server and write http://127.0.0.1:8000/docs I see a focumentation of using this api. that is great, but I do not know the mosque_id that is being used. How could we see the list of the mosque id?

**Comment by MusLead** [comment]
The round way solution is to open the app and share the link of the mosque and open it in the browser. then the address will be shown i.e: https://mawaqit.net/en/m/dawah-kassel .Therefore the mosque-id is `dawah-kassel`

**Comment by mrsofiane** [comment]
Resolved in #10 , fixed the bug in the dockerfile, and added a docker conpose file to run redis and mawaqit api together, also now redis is optional you can enable or disable it via env var.

**Comment by mrsofiane** [comment]
Hello @MusLead, thanks for this wonderful feedback, i'm planning to create a full documentation on how to use this API.

**Comment by highwingers** [comment]
is this offical API from Mawaqit?

**Comment by mrsofiane** [comment]
Hi @highwingers, No this is not an official API from Mawaqit, this api use Mawaqit.net website to get the prayer times in json.

**Comment by mrsofiane** [comment]
Hello @MusLead, a clear documentation is now available here https://mrsofiane.me/mawaqit-api/#/, documentation is generated with docsify, you can check the /docs folder.
